baseURL = "https://avron.gitlab.io/basetemplate/"
languageCode = "en-us"
title = "BaseTemplate"

[params]
    subtitle = "A barebones hugo template"
    [params.main]
        enabled = true
        description = "A barebones hugo template"
        img = "Link to image"
